grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local
    path: /
    pathType: Prefix

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    retention: 2d
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 800Mi
        cpu: 500m

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
